/* Catalogue des guides — rotation saisonnière (les fichiers HTML restent en ligne) */
window.JEUXSTASH_GUIDES = [
  {
    id: "call-of-duty-pas-cher",
    href: "/guides/call-of-duty-pas-cher.html",
    title: "Call of Duty pas cher",
    blurb: "Black Ops 7 : où l’acheter sans se faire avoir.",
    kicker: "Prix",
    thumb: "https://gaming-cdn.com/images/products/15595/616x353/call-of-duty-black-ops-7-pc-battle-net-cover.jpg",
    evergreen: true,
    seasons: ["automne", "hiver"],
  },
  {
    id: "gta-6-pas-cher",
    href: "/guides/gta-6-pas-cher.html",
    title: "GTA 6 pas cher",
    blurb: "Précommande PC : prix, pièges, quand acheter.",
    kicker: "Prix",
    thumb: "https://gaming-cdn.com/images/products/2462/616x353/grand-theft-auto-vi-pc-cover.jpg",
    evergreen: true,
    seasons: ["automne", "hiver", "ete"],
  },
  {
    id: "ea-fc-pas-cher",
    href: "/guides/ea-fc-pas-cher.html",
    title: "EA Sports FC 27 pas cher",
    blurb: "FC 27 : Standard vs promo, faut-il racheter ?",
    kicker: "Sport",
    thumb: "https://gaming-cdn.com/images/products/21656/616x353/ea-sports-fc-27-pc-ea-app-cover.jpg",
    evergreen: true,
    seasons: ["ete", "automne"],
  },
  {
    id: "instant-gaming-fiable",
    href: "/guides/instant-gaming-fiable.html",
    title: "Instant Gaming fiable ?",
    blurb: "Avis clair avant d’acheter une clé.",
    kicker: "Avis",
    evergreen: true,
  },
  {
    id: "acheter-jeux-pas-cher",
    href: "/guides/acheter-jeux-pas-cher.html",
    title: "Payer moins cher",
    blurb: "3 règles. C’est tout.",
    kicker: "Budget",
    evergreen: true,
  },
  {
    id: "cles-jeux-legitimes",
    href: "/guides/cles-jeux-legitimes.html",
    title: "Clés safe",
    blurb: "Éviter les pièges.",
    kicker: "Sécurité",
    evergreen: true,
  },
  {
    id: "forza-horizon-5-pas-cher",
    href: "/guides/forza-horizon-5-pas-cher.html",
    title: "Forza Horizon 5 pas cher",
    blurb: "IG vs Microsoft / Game Pass.",
    kicker: "Prix",
    thumb: "https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/header.jpg",
    seasons: ["ete", "printemps"],
  },
  {
    id: "soldes-steam-payer-moins",
    href: "/guides/soldes-steam-payer-moins.html",
    title: "Soldes Steam",
    blurb: "Payer moins sans wishlist morte.",
    kicker: "Soldes",
    evergreen: true,
  },
  {
    id: "cle-steam-pas-cher",
    href: "/guides/cle-steam-pas-cher.html",
    title: "Clé Steam pas cher",
    blurb: "Où acheter sans se faire avoir.",
    kicker: "Clés",
    evergreen: true,
  },
  {
    id: "baldurs-gate-3-pas-cher",
    href: "/guides/baldurs-gate-3-pas-cher.html",
    title: "Baldur’s Gate 3 pas cher",
    blurb: "GOG / Instant Gaming, quand acheter.",
    kicker: "Prix",
    thumb: "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg",
    seasons: ["hiver", "automne"],
  },
  {
    id: "cyberpunk-pas-cher",
    href: "/guides/cyberpunk-pas-cher.html",
    title: "Cyberpunk pas cher",
    blurb: "Standard vs Ultimate, où l’acheter.",
    kicker: "Prix",
    thumb: "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg",
    seasons: ["hiver", "automne"],
  },
  {
    id: "elden-ring-pas-cher",
    href: "/guides/elden-ring-pas-cher.html",
    title: "Elden Ring pas cher",
    blurb: "Standard ou DLC, où l’acheter.",
    kicker: "Prix",
    thumb: "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg",
    seasons: ["hiver", "automne"],
  },
  {
    id: "jeux-ce-soir-pas-cher",
    href: "/guides/jeux-ce-soir-pas-cher.html",
    title: "Jouer pas cher",
    blurb: "6 idées + liens prix.",
    kicker: "Idées",
    seasons: ["printemps", "ete"],
  },
  {
    id: "game-pass-vs-acheter",
    href: "/guides/game-pass-vs-acheter.html",
    title: "Game Pass ou acheter",
    blurb: "Le calcul en 30 secondes.",
    kicker: "Choix",
    seasons: ["hiver", "printemps"],
  },
  {
    id: "meilleurs-jeux-coop-2026",
    href: "/guides/meilleurs-jeux-coop-2026.html",
    title: "Jeux coop",
    blurb: "Quoi lancer à deux.",
    kicker: "Coop",
    thumb: "https://cdn.cloudflare.steamstatic.com/steam/apps/1426210/header.jpg",
    seasons: ["printemps", "ete"],
  },
  {
    id: "pc-gaming-petit-budget",
    href: "/guides/pc-gaming-petit-budget.html",
    title: "PC petit budget",
    blurb: "Où mettre l’argent.",
    kicker: "PC",
    seasons: ["ete", "automne"],
  },
  {
    id: "meilleurs-jeux-sport-2026",
    href: "/guides/meilleurs-jeux-sport-2026.html",
    title: "Jeux de sport",
    blurb: "Faut-il racheter chaque année ?",
    kicker: "Sport",
    thumb: "https://gaming-cdn.com/images/products/21656/616x353/ea-sports-fc-27-pc-ea-app-cover.jpg",
    seasons: ["ete", "automne"],
  },
];
